### ISSUE TITLE
`mdformat-footnote` plugin strips comments

### ISSUE THREAD

**Issue by kdeldycke** [executablebooks/mdformat-footnote#11]
### Describe the bug

The following Markdown file with a footnote:
```md
I love BSD[^bsd]!

<!-- first comment -->

[^bsd]: FreeBSD, MidnightBSD, NetBSD, OpenBSD, SunOS.

<!-- second comment -->
```

Gets formatted into:
```md
I love BSD[^bsd]!

<!-- first comment -->

<!-- second comment -->

[^bsd]: FreeBSD, MidnightBSD, NetBSD, OpenBSD, SunOS.
```

Instead, I expect `mdformat-footnote` to doesn't touch the second comment and let it in-place, at the end of the file.

### Reproduce the bug

1. Install latest version of `mdformat`:

```shell-session
$ mkdir mdformat-test
$ cd mdformat-test
$ uv venv  
$ source .venv/bin/activate
$ vi test.md
(...)
$ cat test.md
```

```md
I love BSD[^bsd]!

<!-- first comment -->

[^bsd]: FreeBSD, MidnightBSD, NetBSD, OpenBSD, SunOS.

<!-- second comment -->
```

```shell-session
$ uv pip install mdformat            
Resolved 3 packages in 1.73s
Prepared 3 packages in 501ms
Installed 3 packages in 6ms
 + markdown-it-py==3.0.0
 + mdformat==0.7.19
 + mdurl==0.1.2
```

2. Run `mdformat` without plugins:

```shell-session
$ uv run mdformat ./test.md
$ cat test.md
```

```md
I love BSD[^bsd]!

<!-- first comment -->

\[^bsd\]: FreeBSD, MidnightBSD, NetBSD, OpenBSD, SunOS.

<!-- second comment -->
```

As you can see `mdformat` alone is not recognizing footnote syntax and escapes the square brackets. That's why we need `mdformat-footnote` in the first place.

3. Install `mdformat-footnote`:

```shell-session
$ uv pip install mdformat_footnote
Resolved 5 packages in 2.34s
Prepared 2 packages in 388ms
Installed 2 packages in 2ms
 + mdformat-footnote==0.1.1
 + mdit-py-plugins==0.4.2
```

4. Reset `test.md` to its initial form, then reformat it with `mdformat-footnote`:

```shell-session
$ vi test.md
(...)
$ cat ./test.md
```

```md
I love BSD[^bsd]!

<!-- first comment -->

[^bsd]: FreeBSD, MidnightBSD, NetBSD, OpenBSD, SunOS.

<!-- second comment -->
```

```shell-session
$ uv run mdformat ./test.md 
```

```md
I love BSD[^bsd]!

<!-- first comment -->

<!-- second comment -->

[^bsd]: FreeBSD, MidnightBSD, NetBSD, OpenBSD, SunOS.
```

### List your environment

```shell-session
$ uv run mdformat --version
mdformat 0.7.19 (mdformat_footnote 0.1.1)
```

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the footnote rendering logic to preserve the position of comments after footnotes. This change ensures that comments at the end of the file are not moved when formatting footnotes.

You can review changes in this commit: https://github.com/lattaai13/executablebooks-mdformat-footnote-11/commit/5d66aa5bab13f4bd408044495560ff792c409d9c.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by hukkin** [comment]
Thanks for the issue!

I don't think this is a bug. This plugin, by design, [moves footnote definitions](https://github.com/executablebooks/mdformat-footnote/blob/80852fc20cfba7fd0330b9ac7a1a4df983542942/tests/fixtures.md?plain=1#L67) to the end of the document (just before link references).

This is in line with how vanilla mdformat places link references at the bottom.

If you want a comment that doesn't move in relation to the footnote definition, you can add HTML inline on the footnote definition's line.

**Comment by kdeldycke** [comment]
> you can add HTML inline on the footnote definition's line.

Oh good idea. Didn't think of that one. Which makes that workaround good enough to me in my particular case.

Feel free to close this issue then if you think this is not a bug.
